services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIG: local-dev
    ports:
      - "4200:80"

  json-server:
    image: clue/json-server
    ports:
      - "3000:80"
    volumes:
      - ./db.json:/data/db.json