services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIG: dynamic-config
    image: nginx:alpine
    container_name: nginx-frontend
    depends_on:
      - json-server
    volumes:
      - ./dynamic-config/config.json:/usr/share/nginx/html/config.json
    ports:
      - "80:80"
    networks:
      frontend-net:
        ipv4_address: 172.28.0.10

  json-server:
    image: clue/json-server
    volumes:
      - ./db.json:/data/db.json
    networks:
      frontend-net:
        ipv4_address: 172.28.0.20

networks:
  frontend-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16