name: CI for feature branches

on:
  push:
    branches:
     - '**'
#   push:
#     branches-ignore:
#       - main
#       - 'release/**'

jobs:
  static-code-analysis:
    uses: ./.github/workflows/lint-format-typecheck.yml

  tests:
    uses: ./.github/workflows/test.yml
    needs: static-code-analysis