name: CI for feature branches

on:
  push:
    branches-ignore:
      - main
      - 'release/**'
  # push:
  #   branches:
  #     - '**'

jobs:
  static-code-analysis:
    uses: ./.github/workflows/lint-format-typecheck.yml

  tests:
    uses: ./.github/workflows/test.yml
    needs: static-code-analysis