name: End-to-End Tests

on:
  workflow_call:

jobs:
  e2e:
    name: Run Cypress E2E tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Run Cypress tests
        run: npm run test:e2e
        continue-on-error: true  # tymczasowo, żeby nie blokować reszty pipeline'u

      - name: Upload Cypress artifacts (screenshots/videos)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots/
            cypress/videos/
