name: Security Checks

on:
  workflow_call:

jobs:
  synk:
    name: Run Security Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run Snyk Security Test
        run: npm run test:security
        continue-on-error: true
  lint_security:
    name: Run ESLint with Security Plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint with Security Plugin
        run: npm run lint -- --plugin eslint-plugin-security
        continue-on-error: true
