name: Run Unit and Integration Tests with Coverage

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit
        continue-on-error: true

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: ./coverage/lcov-report/index.html

  integration-test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run integration tests
        run: npm run test:integration
        continue-on-error: true
    
      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: ./coverage/lcov-report/index.html
